# Generated by Django 4.1.5 on 2023-06-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_income_date_alter_expense_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='availabe_budget',
            new_name='available_budget',
        ),
    ]
