# Generated by Django 4.1.5 on 2023-06-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_rename_availabe_budget_budget_available_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTEMBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='JANUARY', max_length=20),
        ),
    ]
